security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_SELLER:      [ROLE_USER, ROLE_SELLER]
        ROLE_MANAGER:     [ROLE_USER, ROLE_MANAGER]
        ROLE_ADMIN:       [ROLE_MANAGER, ROLE_SELLER, ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        default:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/change-user-password, role: ROLE_ADMIN }
        - { path: ^/ua-search, role: ROLE_MANAGER }
        - { path: ^/statistics, role: ROLE_SELLER }
        - { path: ^/change-password, role: [ROLE_SELLER, ROLE_MANAGER] }
        - { path: ^/block-user, role: ROLE_ADMIN }
        - { path: ^/service-config, role: ROLE_ADMIN }
        - { path: ^/personification, role: ROLE_SELLER }
        - { path: ^/show-detalization, role: [ROLE_SELLER, ROLE_MANAGER] }
        - { path: ^/show-transactions, role: [ROLE_SELLER, ROLE_MANAGER] }
        - { path: ^/user-edit, role: ROLE_ADMIN }
        - { path: ^/base-service-config, role: ROLE_MANAGER }
        - { path: ^/additional-service-config, role: ROLE_MANAGER }
