security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SELLER:      ROLE_SELLER
        ROLE_MANAGER:     ROLE_MANAGER
        ROLE_ADMIN:       ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        default:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/change-user-password, role: ROLE_ADMIN }
        - { path: ^/ua-search, role: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/statistics, role: [ROLE_ADMIN, ROLE_SELLER] }
        - { path: ^/change-password, role: [ROLE_ADMIN, ROLE_SELLER, ROLE_MANAGER] }
        - { path: ^/block-user, role: ROLE_ADMIN }