# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.query_model:
        class:     AppBundle\Service\QueryModel
        arguments: [@doctrine.dbal.default_connection, @fos_user.user_manager]